sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

language: php

php:
  - 5.6
  - 7.0

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - TEST_DIR=$TRAVIS_BUILD_DIR/src/wcmf/test WCMF_BASE_DIR=$TRAVIS_BUILD_DIR/src

before_script:
  - composer self-update
  - composer install

  - mkdir $WCMF_BASE_DIR/app && mkdir $WCMF_BASE_DIR/install
  - cd $TEST_DIR/model && ant

script:
  - cd $TEST_DIR && phpunit --coverage-clover build/logs/clover.xml --bootstrap bootstrap.php -c configuration.xml
