language: php

php:
  - "5.5"
  - "5.4"
  - "5.3"

env:
  - TEST_DIR=src/wcmf/test

before_script:
  - composer install
  - cd $TEST_DIR/model && ant

script:
  - cd $TEST_DIR && phpunit --bootstrap bootstrap.php -c configuration.xml
