language: php

php:
  - "5.5"
  - "5.4"
  - "5.3"

env:
  - TEST_DIR=$TRAVIS_BUILD_DIR/src/wcmf/test

before_script:
  - composer install

  - wget -q http://dev.wemove.com/wcmf/ChronosGenerator-0.9.9.6b.zip && unzip ChronosGenerator-0.9.9.6b.zip -d generator
  - cd $TEST_DIR/model && ant -Dgenerator.base=generator

script:
  - cd $TEST_DIR && phpunit --bootstrap bootstrap.php -c configuration.xml
